
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloProviders from "@/graphql/client";
import { ReduxProvider } from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  manifest: "/manifest.json",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviders>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </ApolloProviders>
      </body>
    </html>
  );
}
